export const DEFAULT_VISIBILITY_TIMEOUT_IN_SECONDS = 30;
export const MAXIMUM_VISIBILITY_TIMEOUT_IN_SECONDS = 43200;
export const DEFAULT_RECEIVE_MESSAGE_WAIT_TIME_IN_SECONDS = 0;
export const MAXIMUM_RECEIVE_MESSAGE_WAIT_TIME_IN_SECONDS = 20;
export const MINIMUM_MESSAGE_SIZE_IN_BYTES = 1024;
export const MAXIMUM_MESSAGE_SIZE_IN_BYTES = 262144;
