name: Build and Push Image

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Create Tag
        id: set-tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Build Image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/mini-aws-mock:${{ steps.set-tag.outputs.tag }}  --tag ${{ secrets.DOCKER_USERNAME }}/mini-aws-mock:latest
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mini-aws-mock:${{ steps.set-tag.outputs.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/mini-aws-mock:latest
